Added jaxb library to make base64-decode work again on Java11. Extracted from jaxb-ri-2.3.2.zip (sha256: 3cf65ddbd3089d70e3525232421a7e66af91a8d009a460bb09a4b82b3938bbb0 ).
Avoids this error:

Error: #<java bsh.EvalError bsh.EvalError: Sourced file: inline evaluation of: ``new String(javax.xml.bind.DatatypeConverter.parseBase64Binary(data.toString()));'' : Class or variable not found: javax.xml.bind.DatatypeConverter : at Line: 1 : in file: inline evaluation of: ``new String(javax.xml.bind.DatatypeConverter.parseBase64Binary(data.toString()));'' : javax .xml .bind .DatatypeConverter .parseBase64Binary ( data .toString ( ) )
>
bsh.EvalError: Sourced file: inline evaluation of: ``new String(javax.xml.bind.DatatypeConverter.parseBase64Binary(data.toString()));'' : Class or variable not found: javax.xml.bind.DatatypeConverter : at Line: 1 : in file: inline evaluation of: ``new String(javax.xml.bind.DatatypeConverter.parseBase64Binary(data.toString()));'' : javax .xml .bind .DatatypeConverter .parseBase64Binary ( data .toString ( ) )

	at bsh.UtilEvalError.toEvalError(UtilEvalError.java:89)
	at bsh.UtilEvalError.toEvalError(UtilEvalError.java:94)
	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:99)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:102)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:47)
	at bsh.BSHArguments.getArguments(BSHArguments.java:65)
	at bsh.BSHAllocationExpression.objectAllocation(BSHAllocationExpression.java:81)
	at bsh.BSHAllocationExpression.eval(BSHAllocationExpression.java:62)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:102)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:47
	at bsh.Interpreter.eval(Interpreter.java:672)
	at bsh.Interpreter.eval(Interpreter.java:766)
	at bsh.Interpreter.eval(Interpreter.java:755)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sisc.modules.s2j.Operation.invokeMethod(Unknown Source)
	at sisc.modules.s2j.Operation.doApply(Unknown Source)
	at sisc.nativefun.NativeProcedure.apply(Unknown Source)
	at sisc.exprs.AppEval.eval(Unknown Source)
	at sisc.interpreter.Interpreter.next(Unknown Source)
	at sisc.exprs.AppExp.eval(Unknown Source)
	at sisc.interpreter.Interpreter.interpret(Unknown Source)
	at sisc.interpreter.Interpreter.interpret(Unknown Source)
	at sisc.interpreter.Interpreter.eval(Unknown Source)
	at sisc.data.SchemeThread.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: bsh.UtilEvalError: Class or variable not found: javax.xml.bind.DatatypeConverter
	at bsh.Name.consumeNextObjectField(Name.java:343)
	at bsh.Name.toObject(Name.java:202)
	at bsh.Name.toObject(Name.java:185)
	at bsh.Name.invokeMethod(Name.java:832)
	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:75)
	... 24 more
---------------------------
console:393:53: <from call to @iasylum/iasylum::base64-decode>
---------------------------
console:389:1: <from call to irregex-fold>