Improved rhino support. Removed run-js/o (it was not working properly) and added non-optimized version of run/s. It allows code that triggers size-related issues to run properly, avoiding errors such as:
Target exception: org.apache.bsf.BSFException: JavaScript Error: Encountered code generation error while compiling function "39": Program too complex: too big jump offset ((java)#3278)
>
bsh.TargetError: Sourced file: inline evaluation of: ``Object jso = manager.eval("javascript", "(java)", 1, 1, code);       jso.toStrin . . . '' : Typed variable declaration : Method Invocation manager.eval : at Line: 1 : in file: inline evaluation of: ``Object jso = manager.eval("javascript", "(java)", 1, 1, code);       jso.toStrin . . . '' : manager .eval ( "javascript" , "(java)" , 1 , 1 , code )

Target exception: org.apache.bsf.BSFException: JavaScript Error: Encountered code generation error while compiling function "39": Program too complex: too big jump offset ((java)#3278)

Another error example:

igorhvr:~/ $ rhino                                                                                      [7:33:16]
Rhino 1.7 release 4 2013 08 27
js> load("s.js");
js: "s.js", line 3278: Encountered code generation error while compiling function "39": Program too complex: too big jump offset
js>

With optimizations disabled (which is what -opt -1 means) we no longer have issues:

igorhvr:~/ $ rhino -opt -1                                                                              [7:36:33]
Rhino 1.7 release 4 2013 08 27
js>  load("s.js");
js>