Issue fixed: sometimes when the execution was interrupted (exceptions), the current thread lost access to the global logger and further attempts to log caused crashes.
Sample crash prevented by this commit:

Error: #<java bsh.TargetError bsh.TargetError: Sourced file: inline evaluation of: iu.M.d.get("logger-global_48729").get();'' : at Line: 1 : in file: inline evaluation of:iu.M.d.get("logger-global_48729").get();'' : .get ( )

Target exception: java.lang.NullPointerException: Attempt to invoke method get on null value

    bsh.TargetError: Sourced file: inline evaluation of: iu.M.d.get("logger-global_48729").get();'' : at Line: 1 : in file: inline eva luation of:iu.M.d.get("logger-global_48729").get();'' : .get ( )